### ISSUE TITLE
Change author from arista-eosplus to arista

### ISSUE THREAD

**Issue by devrobo** [arista-eosplus/ansible-eos-acl#13]
All the other roles have author set to arista.

**Comment by grybak-arista** [comment]
This is actually an Ansible Galaxy issue that Phil and I discussed quite a while back. There was apparently an update to Galaxy right before the acl role was added where they began applying the github organization as the author. All the other roles had been added prior to that, when the author could be set from within the role files (though I don't remember how at the moment).

Not sure how to address this one. If we delete all the other roles and re-add them to Galaxy, they should be given the author arista-eosplus (I'm guessing). But that may cause issues for users who have installed the roles from Galaxy (no more updates, or need to update their scripts' include statements with the new author name).

**Comment by grybak-arista** [comment]
Closing issue per discussion in Ansible weekly meeting.
